coverage:
  status:
    project:
      default:
        # Commits pushed to main should not make the overall
        # project coverage decrease by more than 1%
        target: auto
        threshold: 1%
    patch:
      default:
        # Don't worry about making changes that aren't tested.
        informational: true
