coverage:
  status:
    project:
      default:
        # Commits pushed to master should not make the overall
        # project coverage decrease by more than 1%.
        target: auto
        threshold: 4%
    patch:
      default:
        # Don't worry about making changes that aren't tested.
        informational: true
