repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args:
            - "--target-version=py36"
            - "--target-version=py37"
            - "--target-version=py38"
            - "--target-version=py39"
        types: [python]
